language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests -w infoqscraper/test/ -w bintest/infoqscraper/ \
      -w bintest/infoqscraper/cache/ -w bintest/infoqscraper/presentation/ 

# build and install the binary
script: "python setup.py install"